permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
name: test
jobs:
  fmt:
    runs-on: windows-latest
    name: checks
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt,clippy
      - name: cargo fmt --check
        run: cargo fmt --check
      - name: clippy 
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: cargo doc
        run: cargo doc --no-deps --all-features
