permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
name: ci
jobs:
  check:
    runs-on: windows-latest
    name: checks
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt,clippy
      - name: cargo fmt --check
        run: cargo fmt --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: cargo doc
        run: cargo doc --no-deps --all-features
        env:
          RUSTFLAGS: -D warnings
  test:
    runs-on: windows-latest
    name: test ${{ matrix.target }}
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc, i686-pc-windows-msvc]
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: cargo test --locked
        run: cargo test --locked --all-targets --target ${{ matrix.target }}

